api = "0.2"

[buildpack]
  id = "paketo-buildpacks/mri"
  name = "Paketo MRI Buildpack"
  homepage = "https://github.com/paketo-buildpacks/mri"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "2.7.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-03-31T00:00:00Z"
    id = "ruby"
    name = "Ruby"
    sha256 = "4749d33a4385cb5cc61dd6e460d474132277fda76cc542e1cdfe45b0df93bdc8"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.8.tar.gz"
    source_sha256 = "6c0bdf07876c69811a9e7dc237c43d40b1cb6369f68e0e17953d7279b524ad9a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.5.8_linux_x64_cflinuxfs3_4749d33a.tgz"
    version = "2.5.8"

  [[metadata.dependencies]]
    deprecation_date = "2021-03-31T00:00:00Z"
    id = "ruby"
    name = "Ruby"
    sha256 = "8e28516b1bc475be4499d31cc5645f46727290fa9bd07745e1def4c71dfe86db"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.9.tar.gz"
    source_sha256 = "f5894e05f532b748c3347894a5efa42066fd11cc8d261d4d9788ff71da00be68"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.5.9_linux_x64_cflinuxfs3_8e28516b.tgz"
    version = "2.5.9"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "a23c26ec93e34ca05328390107ff40034b5103afb91194ebf70f66f0c0866db4"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.gz"
    source_sha256 = "66976b716ecc1fd34f9b7c3c2b07bbd37631815377a2e3e85a5b194cfdcbed7d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.5-linux-x64-cflinuxfs3-a23c26ec.tgz"
    version = "2.6.5"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "7fe47223bd5815df7317e0c3cf3ff1ad75a259d048d759caa9c6eb4db3bea656"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz"
    source_sha256 = "364b143def360bac1b74eb56ed60b1a0dca6439b00157ae11ff77d5cd2e92291"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.6.6_linux_x64_cflinuxfs3_7fe47223.tgz"
    version = "2.6.6"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "c892f69b474a9669320b11b324f1a3efb4bc7a8a6409f4274aef0056a82a2161"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
    source_sha256 = "d418483bdd0000576c1370571121a6eb24582116db0b7bb2005e90e250eae418"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.7.1_linux_x64_cflinuxfs3_c892f69b.tgz"
    version = "2.7.1"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "f675ceed2dd7c64b8b69a3aff39416aff2dff75a8b9e1c309a01a5760968ad9e"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.gz"
    source_sha256 = "6e5706d0d4ee4e1e2f883db9d768586b4d06567debea353c796ec45e8321c3d4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.7.2_linux_x64_cflinuxfs3_f675ceed.tgz"
    version = "2.7.2"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "1f48565be32a9180c66d895a05ffb9142a8e1c7d34b3d7fb74a8f938a9f9aada"
    source = "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz"
    source_sha256 = "a13ed141a1c18eb967aac1e33f4d6ad5f21be1ac543c344e0d6feeee54af8e28"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_3.0.0_linux_x64_cflinuxfs3_1f48565b.tgz"
    version = "3.0.0"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
