api = "0.2"

[buildpack]
  id = "paketo-buildpacks/mri"
  name = "Paketo MRI Buildpack"
  homepage = "https://github.com/paketo-buildpacks/mri"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "2.7.*"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "7fe47223bd5815df7317e0c3cf3ff1ad75a259d048d759caa9c6eb4db3bea656"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz"
    source_sha256 = "364b143def360bac1b74eb56ed60b1a0dca6439b00157ae11ff77d5cd2e92291"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.6.6_linux_x64_cflinuxfs3_7fe47223.tgz"
    version = "2.6.6"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "db90addb4e177bad7478f345e1c4cc4de4eb8326aad5a566678014a0b54c6403"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.7.tar.gz"
    source_sha256 = "e4227e8b7f65485ecb73397a83e0d09dcd39f25efd411c782b69424e55c7a99e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.6.7_linux_x64_cflinuxfs3_db90addb.tgz"
    version = "2.6.7"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "daf118b9a8fb5b629a10d9618c2dd54cfb6904dd88f73fc75f5c18a6ce9e050e"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.3.tar.gz"
    source_sha256 = "8925a95e31d8f2c81749025a52a544ea1d05dad18794e6828709268b92e55338"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.7.3_linux_x64_cflinuxfs3_daf118b9.tgz"
    version = "2.7.3"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "21db42bd63fac78ea7017fb5d5ae357d97ef7de2ed6d08f08164476773c3d6ef"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.4.tar.gz"
    source_sha256 = "3043099089608859fc8cce7f9fdccaa1f53a462457e3838ec3b25a7d609fbc5b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.7.4_linux_x64_cflinuxfs3_21db42bd.tgz"
    version = "2.7.4"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "1f48565be32a9180c66d895a05ffb9142a8e1c7d34b3d7fb74a8f938a9f9aada"
    source = "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz"
    source_sha256 = "a13ed141a1c18eb967aac1e33f4d6ad5f21be1ac543c344e0d6feeee54af8e28"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_3.0.0_linux_x64_cflinuxfs3_1f48565b.tgz"
    version = "3.0.0"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "c1138d6cea76a7906d0611911b1a0ca68b5d5d00d41eb0a60b1622728b1467ad"
    source = "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.gz"
    source_sha256 = "369825db2199f6aeef16b408df6a04ebaddb664fb9af0ec8c686b0ce7ab77727"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_3.0.1_linux_x64_cflinuxfs3_c1138d6c.tgz"
    version = "3.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
